<div class="container-fluid">
    <div>
        <h3>Advertisements System Settings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Advertisements</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Advertisements System Settings</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Advertisements Settings</h6>
                    <div class="ads-settings-alert"></div>
                    <form class="ads-settings" method="POST">

                        <div class="float-left">
                            <label for="user_ads" class="main-label">Advertisements System</label>
                            <br><small class="admin-info">Allow users to create ads.</small>
                        </div>
                        <div class="form-group float-right switcher">
                            <input type="hidden" name="user_ads" value="0" />
                            <input type="checkbox" name="user_ads" id="chck-user_ads" value="1" <?php echo ($wo['config']['user_ads'] == 1) ? 'checked' : ''; ?>>
                            <label for="chck-user_ads" class="check-trail"><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Cost By View</label>
                                <input type="text" id="ad_v_price" name="ad_v_price" class="form-control" value="<?php echo $wo['config']['ad_v_price']; ?>">
                                <small class="admin-info">Set a price for ads impressions.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Cost By Click</label>
                                <input type="text" id="ad_c_price" name="ad_c_price" class="form-control" value="<?php echo $wo['config']['ad_c_price']; ?>">
                                <small class="admin-info">Set a price for ads clicks.</small>
                            </div>
                        </div>
                        <!-- <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="video_ad_skip" name="video_ad_skip" class="form-control" value="<?php echo $wo['config']['video_ad_skip']; ?>">
                                <label class="form-label">Video ads skip button seconds</label>
                            </div>
                        </div> -->
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Top Up <?php echo $wo['user']['name'] ?>'s Wallet</h6>
                    <div class="top-up-settings-alert"></div>
                    <form class="top-up-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Amount</label>
                                <input type="text" id="amount" name="amount" class="form-control" value="<?php echo $wo['user']['wallet']; ?>">
                                <small class="admin-info">You can top your own wallet from here, set any number.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Top Up</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Monetization Settings</h6>
                    <div class="monetization-settings-alert"></div>
                    <form class="monetization-settings" method="POST">

                        <div class="float-left">
                            <label for="monetization_system" class="main-label">Monetization System</label>
                            <div class="dropdown user_filter_drop">
                                <button class="btn btn-light" data-toggle="dropdown">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                        <path fill="currentColor" d="M8 13C6.14 13 4.59 14.28 4.14 16H2V18H4.14C4.59 19.72 6.14 21 8 21S11.41 19.72 11.86 18H22V16H11.86C11.41 14.28 9.86 13 8 13M8 19C6.9 19 6 18.1 6 17C6 15.9 6.9 15 8 15S10 15.9 10 17C10 18.1 9.1 19 8 19M19.86 6C19.41 4.28 17.86 3 16 3S12.59 4.28 12.14 6H2V8H12.14C12.59 9.72 14.14 11 16 11S19.41 9.72 19.86 8H22V6H19.86M16 9C14.9 9 14 8.1 14 7C14 5.9 14.9 5 16 5S18 5.9 18 7C18 8.1 17.1 9 16 9Z">
                                        </path>
                                    </svg>
                                </button>
                                <ul class="dropdown-menu">
                                    <div class="dropdown-menu-innr">
                                        <b>Who can use this feature?</b>
                                        <div>
                                            <div class="round_check">
                                                <input type="radio" name="monetization_request" id="monetization_request-admin" onchange="SelectProModel('can_use_monetization',this)" value="admin" <?php echo ($wo['config']['monetization_request'] == 'admin')   ? ' checked' : ''; ?>>
                                                <label class="radio-inline" for="monetization_request-admin" data-toggle="tooltip" data-placement="bottom" title="Admin"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                                        <path fill="currentColor" d="M12,1L3,5V11C3,16.55 6.84,21.74 12,23C17.16,21.74 21,16.55 21,11V5L12,1M12,5A3,3 0 0,1 15,8A3,3 0 0,1 12,11A3,3 0 0,1 9,8A3,3 0 0,1 12,5M17.13,17C15.92,18.85 14.11,20.24 12,20.92C9.89,20.24 8.08,18.85 6.87,17C6.53,16.5 6.24,16 6,15.47C6,13.82 8.71,12.47 12,12.47C15.29,12.47 18,13.79 18,15.47C17.76,16 17.47,16.5 17.13,17Z">
                                                        </path>
                                                    </svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="monetization_request" id="monetization_request-all" onchange="SelectProModel('can_use_monetization',this)" value="all" <?php echo ($wo['config']['monetization_request'] == 'all')   ? ' checked' : ''; ?>>
                                                <label class="radio-inline" for="monetization_request-all" data-toggle="tooltip" data-placement="bottom" title="All Users"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                                        <path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z">
                                                        </path>
                                                    </svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="monetization_request" id="monetization_request-verified" onchange="SelectProModel('can_use_monetization',this)" value="verified" <?php echo ($wo['config']['monetization_request'] == 'verified')   ? ' checked' : ''; ?>>
                                                <label class="radio-inline" for="monetization_request-verified" data-toggle="tooltip" data-placement="bottom" title="Verified Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                                        <path fill="currentColor" d="M21.1,12.5L22.5,13.91L15.97,20.5L12.5,17L13.9,15.59L15.97,17.67L21.1,12.5M10,17L13,20H3V18C3,15.79 6.58,14 11,14L12.89,14.11L10,17M11,4A4,4 0 0,1 15,8A4,4 0 0,1 11,12A4,4 0 0,1 7,8A4,4 0 0,1 11,4Z">
                                                        </path>
                                                    </svg></label>
                                            </div>
                                            <div class="round_check">
                                                <input type="radio" name="monetization_request" id="monetization_request-pro" onchange="SelectProModel('can_use_monetization',this)" value="pro" <?php echo ($wo['config']['monetization_request'] == 'pro')   ? ' checked' : ''; ?>>
                                                <label class="radio-inline" for="monetization_request-pro" data-toggle="tooltip" data-placement="bottom" title="Pro Users Only"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                                        <path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12M5,13.28L7.45,14.77L6.8,11.96L9,10.08L6.11,9.83L5,7.19L3.87,9.83L1,10.08L3.18,11.96L2.5,14.77L5,13.28Z">
                                                        </path>
                                                    </svg></label>
                                            </div>
                                        </div>
                                    </div>
                                </ul>
                            </div>
                            <br><small class="admin-info">User will earn money from invite users to your site</small>
                        </div>

                        <div class="form-group float-right switcher">
                            <input type="hidden" name="monetization_system" value="0" />
                            <input type="checkbox" name="monetization_system" id="chck-monetization_system" value="1" <?php echo ($wo['config']['monetization_system'] == 1) ? 'checked' : ''; ?> <?php echo (EnableForMode('monetization_system')) ?>>
                            <label for="chck-monetization_system" class="check-trail <?php echo (EnableForMode('monetization_system', true)) ?>" <?php echo (EnableForMode('monetization_system', false, true)) ?>><span class="check-handler"></span></label>
                        </div>
                        <div class="clearfix"></div>
                        <hr>

                        <div class="form-group form-float followers_count">
                            <div class="form-line">
                                <label class="form-label">Followers Count</label>
                                <input type="text" id="followers_count" name="followers_count_to_start_monetization" class="form-control" value="<?php echo $wo['config']['followers_count_to_start_monetization'] ?>">
                                <small class="admin-info">The number of followers to allow users to start a profit
                                    program</small>
                            </div>

                            <div class="form-line">
                                <label class="form-label">Point Earn</label>
                                <input type="text" id="like_mon_point" name="like_mon_point" class="form-control" value="<?php echo $wo['config']['like_mon_point'] ?>">
                                <small class="admin-info">Point earn: for any like of post</small>
                            </div>
                        </div>

                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
    <script>
        $(function() {
            $('.switcher input[type=checkbox]').click(function() {
                setToTrue = 0;
                if ($(this).is(":checked") === true) {
                    setToTrue = 1;
                }
                var configName = $(this).attr('name');
                var hash_id = $('input[name=hash_id]').val();
                var objData = {};
                objData[configName] = setToTrue;
                objData['hash_id'] = hash_id;
                $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
            });

            var setTimeOutColor = setTimeout(function() {});
            $('select').on('change', function() {
                clearTimeout(setTimeOutColor);
                var thisElement = $(this);
                var configName = thisElement.attr('name');
                var hash_id = $('input[name=hash_id]').val();
                var objData = {};
                objData[configName] = this.value;
                objData['hash_id'] = hash_id;
                thisElement.addClass('warning');
                $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function(data) {
                    if (data.status == 200) {
                        thisElement.removeClass('warning');
                        thisElement.addClass('success');
                    } else {
                        thisElement.addClass('error');
                    }
                    var setTimeOutColor = setTimeout(function() {
                        thisElement.removeClass('success');
                        thisElement.removeClass('warning');
                        thisElement.removeClass('error');
                    }, 2000);
                });
            });

            $('input[type=text], input[type=number]').on('input', delay(function() {
                clearTimeout(setTimeOutColor);
                var thisElement = $(this);
                var configName = thisElement.attr('name');
                var hash_id = $('input[name=hash_id]').val();
                var objData = {};
                objData[configName] = this.value;
                objData['hash_id'] = hash_id;
                thisElement.addClass('warning');
                $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function(data) {
                    if (data.status == 200) {
                        thisElement.removeClass('warning');
                        thisElement.addClass('success');
                    } else {
                        thisElement.addClass('error');
                    }
                    var setTimeOutColor = setTimeout(function() {
                        thisElement.removeClass('success');
                        thisElement.removeClass('warning');
                        thisElement.removeClass('error');
                    }, 2000);
                    //thisElement.focus();
                });
            }, 500));

            var form_top_settings = $('form.top-up-settings');
            form_top_settings.ajaxForm({
                url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=top_up_wallet',
                beforeSend: function() {
                    form_top_settings.find('.waves-effect').text('Please wait..');
                },
                success: function(data) {
                    if (data.status == 200) {
                        $("html, body").animate({
                            scrollTop: 0
                        }, "slow");
                        $('.top-up-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Amount added to your wallet successfully.</div>');
                        setTimeout(function() {
                            $('.top-up-settings-alert').empty();
                        }, 2000);
                    }
                    form_top_settings.find('.waves-effect').text('Top Up');
                }
            });
        });
    </script>