<?php
$page                = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$db->pageLimit       = 20;
$total_requests      = $db->getValue(T_USERS, 'COUNT(*)');
$link = "";
$sort_link = $link;
$sort_array = array(
  'DESC_i' => array('id', 'DESC'),
  'ASC_i'  => array('id', 'ASC'),
  'DESC_t' => array('type', 'DESC'),
  'ASC_t'  => array('type', 'ASC')
);
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
  $db->orderBy($sort_array[$_GET['sort']][0], $sort_array[$_GET['sort']][1]);
  $link .= "&sort=" . Wo_Secure($_GET['sort']);
} else {
  $_GET['sort'] = 'DESC_i';
  $db->orderBy('user_id', 'DESC');
}
$users_monetization      = $db->where('monetization', 1)->paginate(T_USERS, $page);

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
  header("Location: " . Wo_LoadAdminLinkSettings('user-monetization-system'));
  exit();
}
$db->where('recipient_id', 0)->where('admin', 1)->where('seen', 0)->where('type', 'verify')->update(T_NOTIFICATION, array('seen' => time()));
?>

<div class="container-fluid">
  <div>
    <h3>Users Monetization System</h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Users</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Users Monetization System</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    <div class="col-lg-12 col-md-12">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Users Monetization System</h6>
          <div class="table-responsive1">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th><input type="checkbox" id="check-all" class="filled-in check-all"><label for="check-all"></label></th>
                  <th>ID
                    <?php if (!empty($_GET['sort']) && $_GET['sort'] == 'DESC_i') { ?>
                      <svg onclick="location.href = '<?php echo (Wo_LoadAdminLinkSettings('user-monetization-system?page-id=1') . $sort_link . "&sort=ASC_i") ?>'" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-up cursor-p">
                        <line x1="12" y1="19" x2="12" y2="5"></line>
                        <polyline points="5 12 12 5 19 12"></polyline>
                      </svg>
                    <?php } else { ?>
                      <svg onclick="location.href = '<?php echo (Wo_LoadAdminLinkSettings('user-monetization-system?page-id=1') . $sort_link . "&sort=DESC_i") ?>'" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-down cursor-p">
                        <line x1="12" y1="5" x2="12" y2="19"></line>
                        <polyline points="19 12 12 19 5 12"></polyline>
                      </svg>
                    <?php } ?>
                  </th>
                  <th>Name</th>
                  <th>Monetization Status</th>
                  <th>Wallet</th>
                  <th>Balaance</th>
                  <th>Points</th>
                  <th>Points By Monetization</th>
                </tr>
              </thead>
              <tbody>
                <?php
                foreach ($users_monetization as $user_monetization) {
                  $wo['user_monetization'] =  Wo_UserData($user_monetization->user_id);
                  echo Wo_LoadAdminPage('user-monetization-system/list');
                }
                ?>
              </tbody>
            </table>
          </div>
          <div class="wo-admincp-feturepager">
            <div class="pull-left">
              <span>
                <?php echo "Showing $page out of " . $db->totalPages; ?>
              </span>
            </div>
            <div class="pull-right">
              <nav>
                <ul class="pagination">
                  <li>
                    <a href="<?php echo Wo_LoadAdminLinkSettings('user-monetization-system?page-id=1') . $link; ?>" data-ajax="?path=user-monetization-system&page-id=1<?php echo ($link); ?>" class="waves-effect" title='First Page'>
                      <i class="material-icons">first_page</i>
                    </a>
                  </li>
                  <?php if ($page > 1) {  ?>
                    <li>
                      <a href="<?php echo Wo_LoadAdminLinkSettings('user-monetization-system?page-id=' . ($page - 1)) . $link; ?>" data-ajax="?path=user-monetization-system&page-id=<?php echo ($page - 1) ?><?php echo ($link); ?>" class="waves-effect" title='Previous Page'>
                        <i class="material-icons">chevron_left</i>
                      </a>
                    </li>
                  <?php  } ?>

                  <?php
                  $nums       = 0;
                  $nums_pages = ($page > 4) ? ($page - 4) : $page;

                  for ($i = $nums_pages; $i <= $db->totalPages; $i++) {
                    if ($nums < 20) {
                  ?>
                      <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                        <a href="<?php echo Wo_LoadAdminLinkSettings('user-monetization-system?page-id=' . ($i)) . $link; ?>" data-ajax="?path=user-monetization-system&page-id=<?php echo ($i) ?><?php echo ($link); ?>" class="waves-effect">
                          <?php echo $i ?>
                        </a>
                      </li>

                  <?php }
                    $nums++;
                  } ?>

                  <?php if ($db->totalPages > $page) { ?>
                    <li>
                      <a href="<?php echo Wo_LoadAdminLinkSettings('user-monetization-system?page-id=' . ($page + 1)) . $link; ?>" data-ajax="?path=user-monetization-system&page-id=<?php echo ($page + 1) ?><?php echo ($link); ?>" class="waves-effect" title="Next Page">
                        <i class="material-icons">chevron_right</i>
                      </a>
                    </li>
                  <?php } ?>
                  <li>
                    <a href="<?php echo Wo_LoadAdminLinkSettings('user-monetization-system?page-id=' . ($db->totalPages)) . $link; ?>" data-ajax="?path=user-monetization-system&page-id=<?php echo ($db->totalPages) ?><?php echo ($link); ?>" class="waves-effect" title='Last Page'>
                      <i class="material-icons">last_page</i>
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-lg-2 col-md-2">
                <span>Action</span>
                <select class="form-control show-tick" id="action_type">
                  <option value="verify">Verify</option>
                  <option value="delete">Delete</option>
                </select>
              </div>
              <div class="col-lg-3 col-md-3">
                <span>&nbsp;</span>
                <button type="button" class="btn btn-info waves-effect delete-selected d-block" disabled>Submit<span></span></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<!-- #END# Vertical Layout -->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal1Label">Delete request?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this request?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="VerifyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal1Label">Verify request?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to Verify this request?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Verify</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal1Label">Delete request?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure that you want to remove the selected request?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">Submit</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('.check-all').on('click', function(event) {
    $('input:checkbox').not(this).prop('checked', this.checked);
  });

  $('.delete-checkbox, .check-all').change(function(event) {
    $('.delete-selected').attr('disabled', false);
    $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
  });

  $('.delete-selected').on('click', function(event) {
    event.preventDefault();
    action_type = $('#action_type').val();
    $('#SelectedDeleteModal').find('.modal-body').html('Are you sure that you want to ' + action_type + ' the selected request(s)?');
    $('#SelectedDeleteModal').find('#exampleModal1Label').html(action_type + ' request(s)');
    $('#SelectedDeleteModal').modal('show');
  });

  function DeleteSelected() {
    action_type = $('#action_type').val();
    data = new Array();
    $('td input:checked').parents('tr').each(function() {
      data.push($(this).attr('data_selected'));
    });
    $('.delete-selected').attr('disabled', true);
    $('.delete-selected').text('Please wait..');
    $.post(Wo_Ajax_Requests_File() + "?f=admin_setting&s=remove_multi_monetization", {
      ids: data,
      type: action_type
    }, function() {
      $.each(data, function(index, value) {
        $("#MonetizationID_" + value + "").remove();
      });
      $('.delete-selected').text('Delete Selected');
    });
  }

  function Wo_DeleteMonetization(id, type = 'show') {
    if (type == 'hide') {
      $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeleteMonetization('" + id + "')");
      $('#DeleteModal').modal('show');
      return false;
    }
    var delete_icon = $('.setting-verification-container').find('#MonetizationID_' + id).find('.delete-verification');
    $('#review-verif-request-info-' + id).slideUp(function() {
      $(this).remove();
      $('#MonetizationID_' + id).fadeOut(300, function() {
        $(this).remove();
      });
    })
    $.get(Wo_Ajax_Requests_File(), {
      f: 'admin_setting',
      s: 'delete_monetization',
      id: id
    });
  }

  function Wo_Verify(id, monetization_id, type = 'show') {
    if (type == 'hide') {
      $('#VerifyModal').find('.btn-primary').attr('onclick', "Wo_Verify('" + id + "','" + monetization_id + "')");
      $('#VerifyModal').modal('show');
      return false;
    }
    console.log(monetization_id);
    var verify_icon = $('.setting-verification-container').find('#MonetizationID_' + monetization_id).find('.verify');
    $('#review-verif-request-info-' + monetization_id).slideUp(function() {
      $(this).remove();
    })
    $('#MonetizationID_' + monetization_id).fadeOut(300, function() {
      $(this).remove();
    });
    $.get(Wo_Ajax_Requests_File(), {
      f: 'admin_setting',
      s: 'monetization_verify_request',
      id: id,
      monetization_id: monetization_id,
      type: type
    });
  }

  $(document).ready(function() {
    $('.review-verif-request-cont a').magnificPopup({
      type: 'image'
    });
  });

  jQuery(document).ready(function($) {
    $(document).on('click', '.toggle-monetization-request', function(event) {
      event.preventDefault();
      $(this).find('i').toggleClass('rotate-90d');
    });
  });
</script>

<style>
  .mfp-bg {
    z-index: 1052;
  }

  .mfp-wrap {
    z-index: 1053;
  }

  .review-verif-request-cont {
    width: 100%;
    overflow: hidden;
    margin: 5px 0;
  }

  .review-verif-request-cont div {
    width: 200px;
    height: 150px;
    float: left;
    cursor: pointer;
    margin: 0 5px 5px 0;
  }

  .review-verif-request-cont h4 {
    width: 100%;
    color: #666;
    font-size: 14px;
    font-weight: 600;
  }

  .toggle-monetization-request {
    padding: 3px 5px;
  }
</style>