<tr class="setting-verificationlist" id="MonetizationID_<?php echo $wo['user_monetization']['user_id'] ?>" data_selected="<?php echo $wo['user_monetization']['user_id'] ?>">
	<td><input type="checkbox" id="check-data-<?php echo $wo['user_monetization']['user_id'] ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['user_monetization']['user_id'] ?>"></label></td>
	<td><?php echo $wo['user_monetization']['user_id'] ?> </td>
	<td>
		<a href="<?php echo $wo['user_monetization']['url']; ?>">
			<img src="<?php echo $wo['user_monetization']['avatar'] ?>" class="setting-avatar rounded-circle" alt="<?php echo ($wo['user_monetization']['first_name'] . ' ' . $wo['user_monetization']['last_name']); ?> Profile Picture">
			<?php echo ($wo['user_monetization']['first_name'] . ' ' . $wo['user_monetization']['last_name']); ?>
		</a>
	</td>
	<td><?php echo $wo['user_monetization']['like_mon'] ? $wo['lang']['active'] :  $wo['lang']['not_active'] ; ?></td>
	<td><?php echo $wo['user_monetization']['wallet']; ?></td>
	<td><?php echo $wo['user_monetization']['balance']; ?></td>
	<td><?php echo $wo['user_monetization']['points']; ?></td>
	<td><?php echo $wo['user_monetization']['monetization_points']; ?></td>
</tr>

<script type="text/javascript">
	$(document).ready(function() {
		$('.image-popup-gallery-item-<?php echo $wo['user_monetization']['user_id']; ?>').magnificPopup({
			type: 'image',
			gallery: {
				enabled: true
			},
			zoom: {
				enabled: true,
				duration: 300,
				easing: 'ease-in-out',
				opener: function(openerElement) {
					return openerElement.is('img') ? openerElement : openerElement.find('img');
				}
			}
		});
	});
</script>