<?php
$wo['is_mon'] = 0;
if ($wo['page'] == 'setting') {
	$wo['is_mon'] = ($db->where('user_id', $wo['user']['id'])->getValue(T_MON_REQUESTS, 'count(*)'));
	if ($wo['is_admin'] && ($wo['user']['monetization'] != 1 || $wo['is_mon'] != 0)) {
		$db->where('user_id', $wo['user']['id'])->update(T_USERS, ['monetization' => 1]);
		if ($wo['is_mon'] != 0) {
			$request_data  = $db->where('user_id', $wo['user']['id'])->getOne(T_MON_REQUESTS);
			if (!empty($request_data)) {
				$db->where('id', $request_data->id)->delete(T_MON_REQUESTS);
				if (file_exists($request_data->personal_photo)) {
					@unlink($request_data->personal_photo);
				}
				if (file_exists($request_data->id_photo)) {
					@unlink($request_data->id_photo);
				}
				@Wo_DeleteFromToS3($request_data->personal_photo);
				@Wo_DeleteFromToS3($request_data->id_photo);
			}
		}
	}
}
?>

<div class="wo_settings_page wow_content">
	<div class="avatar-holder monetization">
		<img src="<?php echo $wo['setting']['avatar'] ?>" alt="<?php echo $wo['setting']['name'] ?> Profile Picture" class="avatar">
		<div class="infoz">
			<h5 title="<?php echo $wo['setting']['name'] ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['setting']['username'] . ''); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>"><?php echo $wo['setting']['name'] ?></a>
			</h5>
			<p><?php echo $wo['lang']['monetization_settings']; ?></p>
		</div>
	</div>
	<hr>

	<?php
	$followers_count = intval($wo['user']['details']['following_count']);
	?>

	<div class="earn_points">
		<div class="ep_illus">
			<?php if ($wo['config']['monetization_system'] == 1 && $wo['is_mon'] == 0 && $wo['setting']['monetization'] == 0) { ?>
				<form method="post" class="form-horizontal monetization-request-form" id="monetization-request-form" enctype="multipart/form-data">
					<div class="monetization-request-alert"></div>

					<div class="row">
						<div class="col-md-12">
							<div class="wow_form_fields">
								<input id="name" name="name" type="text" class="form-control input-md" placeholder="<?php echo $wo['lang']['name']; ?>">
							</div>
						</div>

						<div class="col-md-12">
							<div class="wow_form_fields">
								<textarea id="additional_details" name="additional_details" rows="4" placeholder="<?php echo $wo['lang']['additional_details']; ?>"></textarea>
							</div>
						</div>

						<div class="col-md-12">
							<div class="wow_cset_cover" title="<?php echo $wo['lang']['personal_photo']; ?>">
								<label for="personal_Photo--">Your Personal Photo</label>
								<div class="wow_cset_cover_hdr" id="personal_Photo--">
									<span class="btn btn-file" id="personal_Photo_image-holder" onclick="$('#personal_Photo').trigger('click'); return false;">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
											<path fill="currentColor" d="M14,6L10.25,11L13.1,14.8L11.5,16C9.81,13.75 7,10 7,10L1,18H23L14,6Z" />
										</svg>
									</span>
									<input type="file" class="hidden" id="personal_Photo" accept="image/x-png, image/gif, image/jpeg" name="personal_Photo">
								</div>
							</div>
						</div>

						<div class="col-md-12">
							<div class="wow_cset_cover" title="<?php echo $wo['lang']['passport_Photo']; ?>">
								<label for="passport_Photo--">Your Personal Photo</label>
								<div class="wow_cset_cover_hdr" id="passport_Photo--">
									<span class="btn btn-file" id="passport_Photo_image-holder" onclick="$('#passport_Photo').trigger('click'); return false;">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
											<path fill="currentColor" d="M14,6L10.25,11L13.1,14.8L11.5,16C9.81,13.75 7,10 7,10L1,18H23L14,6Z" />
										</svg>
									</span>
									<input type="file" class="hidden" id="passport_Photo" accept="image/x-png, image/gif, image/jpeg" name="passport_Photo">
								</div>
							</div>
						</div>

					</div>

					<div class="text-center">
						<button type="submit" id="add_wow_loader" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['save']; ?></button>
					</div>

					<input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['setting']['user_id']; ?>">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
				</form>
			<?php } else if ($wo['config']['monetization_system'] == 1 && $wo['is_mon'] > 0 && $wo['setting']['monetization'] == 0) { ?>
				<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail">
						<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
						<polyline points="22,6 12,13 2,6"></polyline>
					</svg><?php echo $wo['lang']['verif_request_received']; ?></div>
			<?php } else { ?>
				<?php if ($followers_count < $wo['config']['followers_count_to_start_monetization']) { ?>
					<div class="alert alert-danger">
						<?php echo str_replace('{followers_count}', $wo['config']['followers_count_to_start_monetization'], $wo['lang']['enable_monetization']); ?>
					</div>

					<div class="c-a">
						<h2 class="text-center">Mersal Monetization Program</h2>
						<div class="cards">
							<div class="col-md-8 card">
								<div class="content m-0 border-radio">
									<div class="subs-icon">
										<i class="fa fa-users"></i>
									</div>
									<div class="w-100">
										<b><?php echo $wo['config']['followers_count_to_start_monetization'] ?></b>
										<br>
										<span>Followers</span>
										<div class="progress">
											<div class="progress-bar" role="progressbar" style="width: <?php echo ($followers_count / $wo['config']['followers_count_to_start_monetization']) * 100; ?>%;" aria-valuenow="<?php echo $followers_count; ?>" aria-valuemin="0" aria-valuemax="<?php echo $wo['config']['followers_count_to_start_monetization']; ?>">
												<?php echo ($followers_count / $wo['config']['followers_count_to_start_monetization']) * 100; ?>%
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php } else { ?>
					<div class="alert alert-info">Enable monetization on your account and start selling posts, get paid from ads, and more.</div>

					<form method="post" class="form-horizontal like-mon-form">
						<div class="like-mon-form-alert"></div>
						<div class="pt_monetize_sett">
							<div class="row">
								<div class="col-md-8" style="padding: 60px;">
									<h4><?php echo str_replace(['{point}', '{like_mon_point}'], ['point', $wo['config']['like_mon_point']], $wo['lang']['earn_mon']); ?></h4>
									<div class="col-md-12 round-check" style="padding: 0;">
										<input type="checkbox" name="toggle-like-monetization" id="toggle-like-monetization" value="1" <?php echo ($wo['setting']['like_mon'] == '1') ? 'checked' : ''; ?>>
										<label for="toggle-like-monetization"><?php echo $wo['lang']['monetization_settings']; ?></label>
									</div>
								</div>
								<div class="col-md-4" style="overflow: hidden;">
									<img class="w-100 h-100" src="<?php echo $wo['config']['theme_url']; ?>/img/money.svg">
								</div>
							</div>
						</div>

						<div class="text-center">
							<!-- <button type="button" id="like_mon_form" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['save']; ?></button> -->
						</div>

						<input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['setting']['user_id']; ?>">
						<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession(); ?>">
					</form>

					<div class="row">
						<div class="col-md-12">
							<div class="counter">
								<div class="col-md-8">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
										<path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-14.243L7.757 12 12 16.243 16.243 12 12 7.757z" />
									</svg>
									<p class="point-text"><?php echo $wo['lang']['points']; ?></p>
									<h2 class="timer count-title count-number" data-to="<?php echo $wo['setting']['monetization_points']; ?>" data-speed="1500"><?php echo $wo['setting']['monetization_points']; ?></h2>
								</div>

								<div class="col-md-4">
									<?php if ($wo['config']['point_allow_withdrawal'] == 1) { ?>
										<p>
											<a class="get_my_earnings_or_wallet" href="<?php echo Wo_SeoLink('index.php?link1=setting&' . $wo['user_setting'] . 'page=payments'); ?>" data-ajax="?link1=setting&<?php echo $wo['user_setting']; ?>page=payments">
												<?php echo $wo['lang']['my_earnings']; ?>
											</a>
										</p>
									<?php } else { ?>
										<p>
											<a class="get_my_earnings_or_wallet" href="<?php echo Wo_SeoLink('index.php?link1=wallet'); ?>">
												<?php echo $wo['lang']['wallet']; ?>
											</a>
										</p>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				<?php } ?>
			<?php } ?>
		</div>
	</div>
</div>

<style>
	.border-radio {
		border-radius: max(0px, min(8px, calc((100vw - 4px - 100%) * 9999))) / 8px;
	}

	.get_my_earnings_or_wallet {
		text-decoration: none !important;
		color: #ff6c22 !important;
		font-size: 20px !important;
		border: 1px dashed #ff6c22 !important;
		padding: 10px !important;
	}

	.get_my_earnings_or_wallet:hover {
		color: #fff !important;
		border: 1px dashed #fff !important;
	}

	.cards {
		width: 100%;
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
	}

	h2 {
		margin-bottom: 20px;
	}

	.progress {
		height: 20px;
		background: #fff7f7;
		margin: 18px 0 0 0;
	}

	.subs-icon {
		width: 30px;
		border: 1px solid #525252;
		border-radius: 50%;
		display: flex;
		justify-content: center;
		align-items: center;
		padding: 9px;
		height: 30px;
		margin: 0 13px;
	}

	.progress-bar {
		color: black;
	}

	.icon-plus {
		display: flex;
		justify-content: center;
		align-items: center;
	}

	.icon-plus img {
		width: 60%;
		height: 60%;
	}

	.card .content {
		border-radius: max(0px, min(8px, calc((100vw - 4px - 100%) * 9999))) / 8px;
		border: 1px solid #525252;
		box-shadow: unset;
		padding: 30px 5px;
		display: flex;
		justify-content: start;
		align-items: center;
	}

	.card .content span {
		font-size: 15px;
	}

	.counter {
		display: flex;
		justify-content: center;
		align-items: center;
	}
</style>

<script type="text/javascript">
	$(function() {

		$("#personal_Photo").on('change', function() {
			$("#personal_Photo_image-holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
		});

		$("#passport_Photo").on('change', function() {
			$("#passport_Photo_image-holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
		});

		$('form.monetization-request-form').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=pages&s=monetization',
			beforeSend: function() {
				$('#add_wow_loader').attr('disabled', true);
				$('.monetization-request-form').find('.add_wow_loader').addClass('btn-loading');
			},
			success: function(data) {
				scrollToTop();
				if (data.status == 200) {
					$('.monetization-request-alert').html('<div class="alert alert-success">' + data.message + '</div>');
					$('.alert-success').fadeIn('fast', function() {
						$(this).delay(2500).slideUp(500, function() {
							$(this).remove();
						});
					});
				} else {
					var errors = data.errors.join("<br>");
					$('.monetization-request-alert').html('<div class="alert alert-danger">' + errors + '</div>');
					$('.alert-danger').fadeIn(300);
				}
				$('.monetization-request-form').find('.add_wow_loader').removeClass('btn-loading');
			}
		});

		$('#toggle-like-monetization').on('change', function() {
			$('form.like-mon-form').ajaxSubmit({
				url: Wo_Ajax_Requests_File() + '?f=pages&s=like_mon_form',
				type: 'POST',
				dataType: 'json',
				beforeSubmit: function() {
					$('#like_mon_form').attr('disabled', true);
					$('.like-mon-form').find('.add_wow_loader').addClass('btn-loading');
				},
				success: function(data) {
					scrollToTop();
					if (data.status == 200) {
						$('.like-mon-form-alert').html('<div class="alert alert-success">' + data.message + '</div>');
						$('.alert-success').fadeIn('fast', function() {
							$(this).delay(2500).slideUp(500, function() {
								$(this).remove();
							});
						});
					} else {
						var errors = data.errors.join("<br>");
						$('.like-mon-form-alert').html('<div class="alert alert-danger">' + errors + '</div>');
						$('.alert-danger').fadeIn(300);
					}
					$('.like-mon-form').find('.add_wow_loader').removeClass('btn-loading');
				}
			});
		});

	});
</script>