<div id="posts">
    <?php
    if ($wo['config']['pro'] == 1) {
        $promoted = $wo['story'] = Wo_GetPromotedPost();
        if (count($promoted) > 0) {
            $wo['story']['post_is_promoted'] = 1;
    ?>
    <div class="promoted-post">
        <span class="promoted-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-award" data-toggle="tooltip" title="<?php echo $wo['lang']['promoted']; ?>">
                <circle cx="12" cy="8" r="7"></circle>
                <polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline>
            </svg> </span>
        <?php echo Wo_LoadPage('story/content'); ?>
    </div>
    <?php }
    } ?>

    <!-- $wo['language_type'] -->
    <?php

    $stories = Wo_GetPosts(array('limit' => 5, 'publisher_id' => 0, 'placement' => 'multi_image_post', 'anonymous' => true));
    if (count($stories) <= 0) {
        echo Wo_LoadPage('story/no-stories');
    } else {
        $isFirstIteration = true;
        foreach ($stories as $index => $wo['story']) {
            if ($index == 1 && $isFirstIteration) {
                echo Wo_GetAd('post_first', false);
                $isFirstIteration = false;
            }
            echo Wo_LoadPage('story/content');
        }
    }
    ?>
</div>
<?php if (count($stories) > 0) { ?>
<div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
    <span class="btn btn-default">
        <i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i>
        &nbsp;<?php echo $wo['lang']['load_more_posts']; ?>
    </span>
</div>
<?php } ?>

<script>
let functionTriggered = false;

function isCloseToElement(element, threshold) {
    const rect = element.getBoundingClientRect();
    const windowHeight = window.innerHeight;
    const elementTop = rect.top;
    const elementBottom = rect.bottom;
    const distanceToElement = Math.min(Math.abs(elementTop - windowHeight), Math.abs(elementBottom));
    console.log(distanceToElement < threshold, distanceToElement, threshold);
    if (distanceToElement < threshold) {
        return true;
    } else {
        functionTriggered = false;
        return false;
    }
}


window.addEventListener('scroll', function() {
    const targetElement = document.querySelector('.sidebar-conatnier');

    if (targetElement && isCloseToElement(targetElement, 200) && !functionTriggered) {
        Wo_GetMorePosts();
        functionTriggered = true;
    }
});
</script>


<!-- .load-more pointer -->
<div id="load-more-filter">
    <span class="filter-by-more hidden" data-filter-by="all"></span>
</div>
<!-- #load-more-filter -->