<div class="page-margin">
	<div class="wowonder-well">
		<br>
		<html>

		<head>
			<style>
				.fa {
					padding: 15px;
					font-size: 15px;
					width: 50px;
					text-align: center;
					text-decoration: none;
					margin: 5px 2px;
				}

				.fa:hover {
					opacity: 0.9;
				}

				.fa-facebook {
					background: #3B5998;
					color: white;
				}

				.fa-content {
					background: #3B5998;
					color: white;
					width: auto;
				}

				.fa-twitter {
					background: #55ACEE;
					color: white;
				}

				.fa-google {
					background: #dd4b39;
					color: white;
				}

				.fa-linkedin {
					background: #007bb5;
					color: white;
				}

				.fa-vk {
					background: #3B5998;
					color: white;
				}

				.fa-whatsapp {
					background: #25d366;
					color: white;
				}
			</style>
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
		</head>

		<body>
			<center>
				<h4><b><i><?php echo $wo['lang']['fbinvite']; ?></i></h4></b>
			</center>
			</br>

			<div id="fb-root"></div>
			<button class="fa-content fa fa-facebook" style="margin:10px;" id='sendbtn' type="button">&nbsp;&nbsp;<?php echo $wo['lang']['fbdesktop']; ?></button>
			<script>
				document.getElementById('sendbtn').onclick = function() {
					FB.init({
						appId: 'XXXXXXXXXXX',
						xfbml: true,
						cookie: true,
						version: 'v9.0'
					});
					FB.ui({
						method: 'send',
						display: 'popup',
						link: 'https://mersal.app',
					}, function(response) {
						if (response && !response.error_message) {
							alert('Your Invitations Have Been Sent Successfully.');
						} else {
							alert('Error while posting.');
						}
					});
				}
			</script>

			</br>
			<a class="fa-content fa fa-commenting" style="margin:10px;" href="fb-messenger://share?link=https://mersal.app" target="_blank">&nbsp;&nbsp;<?php echo $wo['lang']['fbmobile']; ?></a>

			</br>
			<div></br><i>
					<h4><b><?php echo $wo['lang']['share_this_website']; ?></b></h4>
				</i><br>
				<a class="fa fa-facebook" href="https://www.facebook.com/sharer.php?u=https://mersal.app" target="_blank"></a>

				<a class="fa fa-twitter" href="https://twitter.com/intent/tweet?url=https://mersal.app" target="_blank"></a>

				<a class="fa fa-vk" href="https://vk.com/share.php?url=https://mersal.app" target="_blank"></a>

				<a class="fa fa-linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url=https://mersal.app" target="_blank"></a>

				<a class="fa fa-whatsapp" href="https://api.whatsapp.com/send?text=https://mersal.app" target="_blank"></a> <br>
				<br>
			</div>
	</div>
</div>
</body>

</html>